Feature test
findexchange/data-group-service pull request #6
Opened 2016-10-05 10:34 UTC by XiaoPa

* fixed "'ascii' code error;
* updated results field 'rows'

2016-10-05 11:56 UTC, maZahaca requested changes

2016-10-05 11:56 UTC, maZahaca commented on src/flask_app.py
> +		return jsonify({'status': status, 'error':str(e),'results':'no data in the results'}), 400
`results` cannot be different formats
* for success [...] 
* for error "..."

It should be an array all the time, if it's presented in response.

2016-10-05 13:03 UTC, XiaoPa commented on src/flask_app.py
> +		return jsonify({'status': status, 'error':str(e),'results':'no data in the results'}), 400
updated

2016-10-05 14:25 UTC, maZahaca requested changes

2016-10-05 14:25 UTC, maZahaca commented on src/flask_app.py
> +		return jsonify({'error':str(e),'status': status, 'results':"[no data in the results]"}), 400
This is still wrong format.
* I mean if we have a error, we don't need to set results or set it as an empty array `[]`.
   * results is only available for providing results of grouping, if we didn't group anything, so it's nothing to provide
* above variable `results` is unused

2016-10-05 14:32 UTC, XiaoPa commented on src/flask_app.py
> +		return jsonify({'error':str(e),'status': status, 'results':"[no data in the results]"}), 400
so I just leave results as empty array:
e.g 
jsonify({'status': status, 'error':str(e),'results':'[]'}), 400
or 
jsonify({'status': status, 'error':str(e)}), 400

2016-10-05 15:05 UTC, maZahaca commented on src/flask_app.py
> +		return jsonify({'error':str(e),'status': status, 'results':"[no data in the results]"}), 400
better `jsonify({'status': status, 'error':str(e)}), 400`

2016-10-06 09:18 UTC, merged

2016-10-06 09:19 UTC, maZahaca commented
Good job, thanks